from __future__ import annotations

import json

from aethergraph.classifier import estimate_tokens
from aethergraph.providers.base import ModelProvider
from aethergraph.types import CompletionRequest, CompletionResult, ModelProfile, TaskType


class MockProvider(ModelProvider):
    name = "mock"

    def available(self, profile: ModelProfile) -> bool:
        return profile.provider == self.name

    async def complete(self, profile: ModelProfile, request: CompletionRequest) -> CompletionResult:
        prompt = request.prompt
        if "json" in prompt.lower():
            text = json.dumps(
                {
                    "facts": ["mock fact"],
                    "constraints": ["keep cost low"],
                    "deliverable": "structured result",
                    "model": profile.id,
                }
            )
        elif profile.capabilities.get(TaskType.CODE, 0) >= 7:
            text = (
                f"// generated by {profile.id}\n"
                "function routeTask(task) {\n"
                "  return task.type === 'code' ? 'local-coder' : 'cheap-cloud';\n"
                "}\n"
            )
        else:
            text = f"[{profile.id}] {prompt[:240]}"
        return CompletionResult(
            text=text,
            input_tokens=estimate_tokens(prompt),
            output_tokens=estimate_tokens(text),
            model=profile.model,
            provider=self.name,
        )
